import { createContext, useContext, useEffect, useMemo, useRef, useState } from 'react'

const mr = {
  Dashboard: 'डॅशबोर्ड',
  'Product Stock': 'प्रॉडक्ट स्टॉक',
  'Purchase Stock': 'खरेदी स्टॉक',
  Sales: 'विक्री',
  'Scrap Stock': 'स्क्रॅप स्टॉक',
  Inventory: 'इन्व्हेंटरी',
  Reports: 'रिपोर्ट',
  Settings: 'सेटिंग्ज',
  Admin: 'अ‍ॅडमिन',
  English: 'इंग्रजी',
  Marathi: 'मराठी',
  Print: 'प्रिंट',
  Close: 'बंद करा',
  Cancel: 'रद्द करा',
  Save: 'सेव्ह करा',
  Edit: 'बदल करा',
  Delete: 'डिलीट',
  See: 'पहा',
  Search: 'शोधा',
  Reset: 'रीसेट',
  Date: 'तारीख',
  Customer: 'ग्राहक',
  Company: 'कंपनी',
  Invoice: 'बिल',
  'Invoice No.': 'बिल नं.',
  'Invoice Number': 'बिल नंबर',
  'Customer Name': 'ग्राहकाचे नाव',
  'Phone Number': 'फोन नंबर',
  Phone: 'फोन',
  Address: 'पत्ता',
  GSTIN: 'GSTIN',
  'Customer GSTIN': 'ग्राहक GSTIN',
  'Vehicle Name': 'वाहनाचे नाव',
  'Vehicle Number': 'वाहन नंबर',
  'Serial No.': 'सिरीयल नं.',
  'Serial Number': 'सिरीयल नंबर',
  HSN: 'HSN',
  Qty: 'नग',
  Quantity: 'नग',
  Units: 'युनिट',
  Rate: 'दर',
  Discount: 'सवलत',
  Total: 'एकूण',
  Amount: 'रक्कम',
  Status: 'स्थिती',
  Paid: 'भरले',
  Due: 'बाकी',
  'Paid Amount': 'भरलेली रक्कम',
  'Due Amount': 'बाकी रक्कम',
  'Total Amount': 'एकूण रक्कम',
  'Payment Method': 'पेमेंट पद्धत',
  'Payment History': 'पेमेंट इतिहास',
  'Battery Information': 'बॅटरी माहिती',
  'Customer Information': 'ग्राहक माहिती',
  'Company Details': 'कंपनी तपशील',
  'invoices today': 'आजची इनव्हॉइस',
  'customers pending': 'पेंडिंग ग्राहक',
  'purchase entries': 'खरेदी नोंदी',
  'vendors pending':'प्रलंबित पुरवठादार',
  'No customer dues recorded.':'कोणतीही ग्राहक देयके नोंदवलेली नाहीत.',
  'Pending Purchase Dues':'प्रलंबित खरेदी देयके',
  'No purchase dues recorded.':'कोणतीही खरेदी देय रक्कम नोंदवलेली नाही.',
  'Add up to 15 serial numbers in this batch â€” scan them one by one or type them in below.':'या बॅचमध्ये १५ पर्यंत अनुक्रमांक (serial numbers) समाविष्ट करा — ते एक-एक करून स्कॅन करा किंवा खाली टाईप करा.',
  'Battery': 'बॅटरी',
  'Action':'कृती',
  'Purchase Model':'खरेदी मॉडेल',
  'HSN Number':'HSN नंबर',
  'Add Units':'युनिट्स जोडा',
  'Per Total Price':'एकूण प्रति किंमत',
  '| Remaining Due:':'| शिल्लक देय रक्कम:',
  'No purchase stock added yet.':'अद्याप कोणताही खरेदी केलेला साठा जोडलेला नाही.',
  'Remaining Due':'शिल्लक देय रक्कम',
  'Paid Amount (₹)':'भरलेली रक्कम (₹)',
  'Due Amount (₹)':'देय रक्कम (₹)',
  'Battery Total Including GST' :'GST बॅटरीची एकूण किंमत',
  'Old Battery Total Including GST' :'जुनी बॅटरी GST सह एकूण रक्कम',
  'Battery Price Before GST' :'जीएसटी-पूर्व बॅटरीची किंमत',
  'Price Summary': 'किंमतीचा सारांश',
  'Battery Total' :'एकूण बॅटरी',
  'Taxable Amount':'करपात्र रक्कम',
  'Preview':'पूर्वावलोकन',
  'Per Price':'प्रति किंमत',
  'Last Total Price:':'शेवटची एकूण किंमत:',
  'Invoice:':'बील:',
  'Customer:':'ग्राहक:',
  'Payment:':'पेमेंट:',
  'Old Battery purchase':'जुनी बॅटरी खरेदी',
  'Paid:':'भरले:',
  'Remaining Due:':'शिल्लक देय रक्कम',
  'Purchase History':'खरेदी इतिहास',
  'Add purchase entries, dues, ledger, and print records':'खरेदीच्या नोंदी, येणे बाकी, लेजर आणि प्रिंट रेकॉर्ड्स जोडा.',
  'Create and manage battery sales invoices':'बॅटरी विक्रीची बिले तयार करा आणि व्यवस्थापित करा.',
  'Sales Invoice': 'विक्री बिल',
  'Old battery stock and company sales management':'जुना बॅटरी साठा आणि कंपनी विक्री व्यवस्थापन',
  'Kg available':'किलो उपलब्ध',
  'Click Bike Batteries or Car Batteries to view and search their records.':'दुचाकी किंवा कारच्या बॅटरींचे तपशील पाहण्यासाठी आणि शोधण्यासाठी संबंधित पर्यायावर क्लिक करा.',
  'Address / Phone':'पत्ता/फोन',
  'companies ·':'कंपनी ·',
  'No company scrap sales have been added yet.':'यात कंपनीच्या स्क्रॅप विक्रीचा समावेश केलेला नाही.',
  'Sales':'विक्री',
  'sales':'विक्री',
  'Old Battery Weight (Kg)':'जुनी बॅटरी वजन (Kg)',
   'New Customer':'नवीन ग्राहक',
   'Existing Customer':'विद्यमान ग्राहक',
  'Sales, purchase, due, and brand performance':'विक्री, खरेदी, देय रक्कम आणि ब्रँडची कामगिरी',
  'invoices':'बिल',
  'entries':'नोंद',
  'Select existing customer':'विद्यमान ग्राहक निवडा',
  'This customer will be available in the existing customer list after saving the sale.':'विक्रीची नोंद केल्यानंतर हा ग्राहक विद्यमान ग्राहकांच्या यादीत उपलब्ध होईल.',
  'Regular Sale':'नियमित विक्री',
  'Old Battery':'जुनी बॅटरी',
   'Type of Battery' :'बॅटरीचा प्रकार',
   'Model / Capacity' :'मॉडेल / क्षमता',
   'Scan Model / Capacity and Serial Number' :'मॉडेल / क्षमता आणि अनुक्रमांक स्कॅन करा',
   'Invoice Information': 'इन्व्हॉईस माहिती',
   'Vehicle Information':'वाहनाची माहिती',
   'Print Preview':'प्रिंट पूर्वदृश्य',
   'Save Sale':'विक्री जतन करा',
   'Type of Battery *':'बॅटरीचा प्रकार *',
  'Send Daily Sales':'दैनंदिन विक्रीची माहिती पाठवा',
  'Send Daily Scrap Sales':'दैनिक स्क्रॅप विक्री पाठवा',
  'See more':'अधिक पहा',
  'Sales':'विक्री',
  'Enter current password': 'सध्याचा पासवर्ड प्रविष्ट करा',
  'Name':'नाव',
  'Brand & Capacity':'ब्रँड आणि क्षमता',
  'Type of Vehicle':'वाहनाचा प्रकार',
  'Payment and Notes':'पेमेंट आणि नोंद',
  'Unit':'युनिट',
  'No regular sales found.':'कोणतीही नियमित विक्री आढळली नाही.',
  'Battery Details':'बॅटरीचा तपशील',
  'Type of Battery *':'बॅटरीचा प्रकार *',
  'Save Purchase':'खरेदी जतन करा',
  'Create a new battery sales invoice': 'नवीन बॅटरी विक्री बिल तयार करा',
  'Regular Sales': 'रेग्युलर विक्री',
  'Old Stock': 'जुना स्टॉक',
  'Sell Old Stock': 'जुना स्टॉक विक्री',
  'Scrap Stock Details': 'स्क्रॅप स्टॉक तपशील',
  'Scrap Sale Details': 'स्क्रॅप विक्री तपशील',
  'Customer Old Battery Scrap Report': 'ग्राहक जुनी बॅटरी स्क्रॅप रिपोर्ट',
  'Complete old battery information and stock search': 'जुन्या बॅटरीची संपूर्ण माहिती व स्टॉक शोध',
  'Kalyankar Batteries': 'कल्याणकर बॅटरीज',
  'Certified With Excellent Quality': 'उत्कृष्ट गुणवत्तेसह प्रमाणित',
  'Gargoti - Kolhapur main road, Gargoti 416209': 'शिंदे कॉम्प्लेक्स, मेन रोड, गारगोटी, ता. भुदरगड, जि. कोल्हापूर, 416209',
  'Gargoti - Kolhapur Road, Gargoti, Near Swami Samarth Mangal Karyalay': 'शिंदे कॉम्प्लेक्स, मेन रोड, गारगोटी, स्वामी समर्थ मंगल कार्यालयाजवळ',
  'Near Swami samarth mangal karyalay': 'स्वामी समर्थ मंगल कार्यालयाजवळ',
  'Daily battery shop overview': 'दैनिक बॅटरी दुकानाचा आढावा',
  "Today's Sales": 'आजची विक्री',
  'Sales Due': 'विक्री बाकी',
  'Purchase Total': 'एकूण खरेदी',
  'Purchase Due': 'खरेदी बाकी',
  'Money Position': 'पैशांची स्थिती',
  'Purchase Paid': 'खरेदी भरलेली',
  'Pending Customer Payments': 'ग्राहकांचे बाकी पेमेंट',
  'Open Sales': 'विक्री उघडा',
  'Open Purchase': 'खरेदी उघडा',
  'Recent Sales': 'अलीकडील विक्री',
  'View All': 'सर्व पहा',
  'Quick Actions': 'जलद कृती',
  'Add Purchase': 'खरेदी जोडा',
  'New Sale': 'नवीन विक्री',
  'Track batteries by brand, model & serial number': 'ब्रँड, मॉडेल आणि सिरीयल नंबरनुसार बॅटरी ट्रॅक करा',
  'Battery Brands': 'बॅटरी ब्रँड',
  'Total Models': 'एकूण मॉडेल',
  'Live Stock Units': 'उपलब्ध स्टॉक युनिट',
  'Low Stock': 'कमी स्टॉक',
  'Out of Stock': 'स्टॉक संपला',
  'In Stock': 'स्टॉकमध्ये',
  'Add Brand': 'ब्रँड जोडा',
  'All Brands': 'सर्व ब्रँड',
  'Add Model': 'मॉडेल जोडा',
  'Print Receipt': 'पावती प्रिंट करा',
  'Import Excel': 'एक्सेल इम्पोर्ट करा',
  'Add Serial Number': 'सिरीयल नंबर जोडा',
  'Report Type': 'रिपोर्ट प्रकार',
  'Full Overview': 'संपूर्ण आढावा',
  'Sales Only': 'फक्त विक्री',
  'Purchase Only': 'फक्त खरेदी',
  'Dues Only': 'फक्त बाकी',
  'From': 'पासून',
  'To': 'पर्यंत',
  'Print Report': 'रिपोर्ट प्रिंट करा',
  'Total Sales': 'एकूण विक्री',
  'Units Sold': 'विकलेले युनिट',
  'Purchase Amount': 'खरेदी रक्कम',
  'Total Outstanding': 'एकूण बाकी',
  'Money Report': 'पैशांचा रिपोर्ट',
  'Sales By Brand': 'ब्रँडनुसार विक्री',
  'Top Selling Models': 'सर्वाधिक विकलेले मॉडेल',
  'Brand Performance': 'ब्रँड कामगिरी',
  'Customer Due Report': 'ग्राहक बाकी रिपोर्ट',
  'Purchase Due Report': 'खरेदी बाकी रिपोर्ट',
  'Stock Report': 'स्टॉक रिपोर्ट',
  'Regular Sale Report': 'रेग्युलर विक्री रिपोर्ट',
  'Old Stock Sale Report': 'जुना स्टॉक विक्री रिपोर्ट',
  'Scrap Stock Sell Report': 'स्क्रॅप स्टॉक विक्री रिपोर्ट',
  Brand: 'ब्रँड',
  Model: 'मॉडेल',
  Revenue: 'उत्पन्न',
  Weight: 'वजन',
  'No sales found.': 'विक्री सापडली नाही.',
  'Add Serial': 'सिरियल जोडा',
  'Add Models': 'मॉडेल जोडा',
  'Add Serial Numbers': 'सिरियल नंबर जोडा',
  'Scan Model Name': 'मॉडेल नाव स्कॅन करा',
  'Scan Serial Number': 'सिरियल नंबर स्कॅन करा',
  'Scan with barcode scanner or enter': 'बारकोड स्कॅनरने स्कॅन करा किंवा प्रविष्ट करा',
  manually: 'स्वतः टाका',
  'Use Value': 'वापरा',
  'Point the camera at the barcode, or click the box below and use your USB barcode scanner.': 'कॅमेरा बारकोडकडे ठेवा किंवा खालील बॉक्सवर क्लिक करून USB बारकोड स्कॅनर वापरा.',
  'Camera scanner could not start. You can still use a USB barcode scanner or type below.': 'कॅमेरा स्कॅनर सुरू होऊ शकला नाही. तुम्ही USB बारकोड स्कॅनर वापरू शकता किंवा खाली टाइप करू शकता.',
  Warranty: 'वॉरंटी',
  Days: 'दिवस',
  Months: 'महिने',
  Years: 'वर्षे',
  'Purchase Price (₹)': 'खरेदी किंमत (₹)',
  'Selling Price (₹) *': 'विक्री किंमत (₹) *',
  'Select model': 'मॉडेल निवडा',
  'No serial numbers yet.': 'अजून सिरियल नंबर नाहीत.',
  'Remove serial number': 'सिरियल नंबर काढा',
  'Delete model': 'मॉडेल हटवा',
  'Across all brands': 'सर्व ब्रँडमध्ये',
  'Serial numbers in stock': 'स्टॉकमधील सिरियल नंबर',
  '5 or fewer units left': '५ किंवा कमी युनिट शिल्लक',
  'Needs restocking': 'पुन्हा स्टॉक भरणे आवश्यक',
  Batteries: 'बॅटरी',
  model: 'मॉडेल',
  models: 'मॉडेल',
  battery: 'बॅटरी',
  batteries: 'बॅटरी',
  'in stock': 'स्टॉकमध्ये',
  'Search by model name...': 'मॉडेल नावाने शोधा...',
  'No models yet for this brand. Click "Add Model" to create one.': 'या ब्रँडसाठी अजून मॉडेल नाहीत. नवीन मॉडेल तयार करण्यासाठी "मॉडेल जोडा" वर क्लिक करा.',
  'No models match your search.': 'तुमच्या शोधाशी जुळणारे मॉडेल सापडले नाही.',
  'Brand Name *': 'ब्रँड नाव *',
  'Enter brand name': 'ब्रँड नाव टाका',
  'Model(s)': 'मॉडेल',
  'From Date': 'सुरुवातीची तारीख',
  'To Date': 'शेवटची तारीख',
  'Separate multiple model names with a comma. Leave blank to include every model.': 'अनेक मॉडेल नावे स्वल्पविरामाने वेगळी करा. सर्व मॉडेल समाविष्ट करण्यासाठी रिकामे ठेवा.',
  'Leave both dates blank to include every date.': 'सर्व तारखा समाविष्ट करण्यासाठी दोन्ही तारखा रिकाम्या ठेवा.',
  Models: 'मॉडेल',
  'Model Name': 'मॉडेल नाव',
  'Serial Numbers': 'सिरियल नंबर',
  'Add up to 15 model names in this batch. Camera scan, USB barcode scanner, and typing all work here.': 'या बॅचमध्ये जास्तीत जास्त १५ मॉडेल नावे जोडा. कॅमेरा स्कॅन, USB बारकोड स्कॅनर आणि टायपिंग येथे वापरता येते.',
  Profile: 'प्रोफाइल',
  'Business Info': 'व्यवसाय माहिती',
  Notifications: 'सूचना',
  Security: 'सुरक्षा',
  Backup: 'बॅकअप',
  'Manage your account and business preferences': 'तुमचे खाते आणि व्यवसाय प्राधान्ये व्यवस्थापित करा',
  'Profile Details': 'प्रोफाइल तपशील',
  'Full Name': 'पूर्ण नाव',
  Email: 'ईमेल',
  Role: 'भूमिका',
  'Save Changes': 'बदल जतन करा',
  'Business Information': 'व्यवसाय माहिती',
  'Business Name': 'व्यवसायाचे नाव',
  'Contact Number': 'संपर्क क्रमांक',
  Currency: 'चलन',
  'Notification Preferences': 'सूचना प्राधान्ये',
  'Low Stock Alerts': 'कमी स्टॉक सूचना',
  'Get notified when a product falls below reorder level': 'उत्पादनाचा स्टॉक पुनर्भरण पातळीपेक्षा कमी झाल्यावर सूचना मिळवा',
  'Payment Due Reminders': 'बाकी पेमेंट स्मरणपत्रे',
  'Alerts for customers with pending dues': 'बाकी रक्कम असलेल्या ग्राहकांसाठी सूचना',
  'Warranty Expiry Alerts': 'वॉरंटी संपण्याच्या सूचना',
  'Notify 30 days before a warranty expires': 'वॉरंटी संपण्यापूर्वी ३० दिवस सूचना द्या',
  'Daily Sales Summary (Email)': 'दैनिक विक्री सारांश (ईमेल)',
  'Receive a daily summary of sales and orders': 'विक्री आणि ऑर्डरचा दैनिक सारांश मिळवा',
  'Change Password': 'पासवर्ड बदला',
  'Current Password': 'सध्याचा पासवर्ड',
  'New Password': 'नवीन पासवर्ड',
  'Confirm New Password': 'नवीन पासवर्डची पुष्टी करा',
  'Update Password': 'पासवर्ड बदला',
  'Backup & Data': 'बॅकअप आणि डेटा',
  'Create a backup of your products, sales, and customer data, or restore from a previous backup file.': 'उत्पादने, विक्री आणि ग्राहक डेटाचा बॅकअप तयार करा किंवा आधीच्या बॅकअपमधून पुनर्संचयित करा.',
  'Create Backup': 'बॅकअप तयार करा',
  'Restore Backup': 'बॅकअप पुनर्संचयित करा',
  'Last Backup': 'शेवटचा बॅकअप',
  'No backup created yet.': 'अजून बॅकअप तयार केलेला नाही.',
  'Changes saved successfully.': 'बदल यशस्वीरीत्या जतन केले.',
  'Battery quantity': 'बॅटरीची संख्या',
  'Customer + purchase dues': 'ग्राहक आणि खरेदी बाकी',
  Purchase: 'खरेदी',
  Selling: 'विक्री किंमत',
  'No stock found.': 'स्टॉक सापडला नाही.',
  'No old stock sales found.': 'जुन्या स्टॉकची विक्री सापडली नाही.',
  'No customer dues found.': 'ग्राहकांची बाकी सापडली नाही.',
  'No purchase dues found.': 'खरेदीची बाकी सापडली नाही.',
  Category: 'वर्ग',
  'No scrap stock sales found.': 'स्क्रॅप स्टॉक विक्री सापडली नाही.',
  'Total Orders': 'एकूण ऑर्डर',
  'All invoices': 'सर्व बिले',
  'Invoices raised': 'तयार केलेली बिले',
  'Invoices settled': 'भरलेली बिले',
  'Pending collection': 'वसुली बाकी',
  'Create New Sale': 'नवीन विक्री तयार करा',
  'Select existing customer': 'विद्यमान ग्राहक निवडा',
  'GST Number (Optional)': 'GST क्रमांक (ऐच्छिक)',
  'Select Brand': 'ब्रँड निवडा',
  'Select Battery Type': 'बॅटरी प्रकार निवडा',
  'Discount (%)': 'सवलत (%)',
  'CGST Rate': 'CGST दर',
  'SGST Rate': 'SGST दर',
  'Total GST': 'एकूण GST',
  'Total Warranty': 'एकूण वॉरंटी',
  'Warranty Type (Optional)': 'वॉरंटी प्रकार (ऐच्छिक)',
  'Select Warranty Type': 'वॉरंटी प्रकार निवडा',
  'Invoice Date': 'बिल तारीख',
  'Sales Person': 'विक्री कर्मचारी',
  'Select Payment Method': 'पेमेंट पद्धत निवडा',
  'Payment Status': 'पेमेंट स्थिती',
  Notes: 'टिप्पणी',
  Subtotal: 'उपएकूण',
  'Grand Total': 'एकूण रक्कम',
  'Present Quantity': 'सध्याची संख्या',
  'Present Weight': 'सध्याचे वजन',
  'Bike and car batteries': 'बाईक आणि कार बॅटरी',
  'Total scrap available': 'उपलब्ध एकूण स्क्रॅप',
  'Bike Battery Stock': 'बाईक बॅटरी स्टॉक',
  'Car Battery Stock': 'कार बॅटरी स्टॉक',
  available: 'उपलब्ध',
  'Print language': 'प्रिंट भाषा',
  'Bike Rate per Kg (₹) *': 'बाईक दर प्रति किलो (₹) *',
  'Car Rate per Kg (₹) *': 'कार दर प्रति किलो (₹) *',
  'Bike Rate per Kg': 'बाईक दर प्रति किलो',
  'Car Rate per Kg': 'कार दर प्रति किलो',
  'Bike Rate': 'बाईक दर',
  'Car Rate': 'कार दर',
  'Bike Batteries': 'बाईक बॅटरी',
  'Car Batteries': 'कार बॅटरी',
  'Click to view all bike battery details': 'सर्व बाईक बॅटरी तपशील पाहण्यासाठी क्लिक करा',
  'Click to view all car and other battery details': 'सर्व कार व इतर बॅटरी तपशील पाहण्यासाठी क्लिक करा',
  'Total Added': 'एकूण जोडले',
  'Total Sold': 'एकूण विकले',
  'Present Stock': 'सध्याचा स्टॉक',
  'Scrap Sold to Companies': 'कंपन्यांना विकलेला स्क्रॅप',
  'Every old-stock sale is shown as a separate company transaction': 'प्रत्येक जुन्या स्टॉकची विक्री स्वतंत्र कंपनी व्यवहार म्हणून दाखवली आहे',
  'Old Batteries': 'जुन्या बॅटऱ्या',
  Actions: 'कृती',
  'Total Weight': 'एकूण वजन',
  'Scrap Type': 'स्क्रॅप प्रकार',
  'Rate / Kg': 'दर / किलो',
  'See scrap sale details': 'स्क्रॅप विक्री तपशील पहा',
  Ledger: 'खातेवही',
  'Record Payment': 'पेमेंट नोंदवा',
  'Print Invoice': 'बिल प्रिंट करा',
  'Payment Summary': 'पेमेंट सारांश',
  'No payments recorded yet.': 'अजून पेमेंट नोंदलेले नाही.',
  'Company Name': 'कंपनीचे नाव',
  'Scrap Purchased': 'खरेदी केलेला स्क्रॅप',
  'Pay Due': 'बाकी भरा',
  'Print Full Ledger': 'पूर्ण खातेवही प्रिंट करा',
  Cash: 'रोख',
  Card: 'कार्ड',
  'Bank Transfer': 'बँक ट्रान्सफर',
  Cheque: 'चेक',
  Other: 'इतर',
  'Save Payment': 'पेमेंट जतन करा',
}

// Labels added by the newer Purchase, Sales and Scrap Stock screens.
// Keep page text here so switching the main language always translates new UI work too.
Object.assign(mr, {
  'Save, Print & WhatsApp': 'जतन, प्रिंट आणि व्हाट्सअँप',
  'System Alerts': 'सिस्टम सूचना',
  'Alerts when a battery model has 5 or fewer units.': 'बॅटरी मॉडेलमध्ये 5 किंवा त्यापेक्षा कमी नग असताना सूचना.',
  'Alerts for customers with pending sale payments.': 'विक्री पेमेंट बाकी असलेल्या ग्राहकांसाठी सूचना.',
  'Alerts for pending payments to purchase companies.': 'खरेदी कंपन्यांची पेमेंट बाकी असल्यास सूचना.',
  'Alerts when scrap-sale payments are pending.': 'स्क्रॅप विक्रीची पेमेंट बाकी असल्यास सूचना.',
  'Alerts 30 days before a customer warranty expires.': 'ग्राहकाची वॉरंटी संपण्यापूर्वी 30 दिवस आधी सूचना.',
  'Daily sales, purchase, and scrap-sale summary.': 'दैनिक विक्री, खरेदी आणि स्क्रॅप विक्री सारांश.',
  'Reminder when no backup was created in the last 7 days.': 'मागील 7 दिवसांत बॅकअप तयार केला नसल्यास स्मरणपत्र.',
  'Success and failure alerts for PDF, backup, and email activity.': 'PDF, बॅकअप आणि ईमेल प्रक्रियेच्या यशस्वी किंवा अयशस्वी सूचना.',
  'unread': 'न वाचलेल्या',
  'Mark All as Read': 'सर्व वाचले म्हणून चिन्हांकित करा',
  'Clear All': 'सर्व साफ करा',
  'Notification Settings': 'सूचना सेटिंग्ज',
  'No notifications': 'कोणत्याही सूचना नाहीत',
  'Low Stock': 'कमी स्टॉक',
  'Customer Payment Due': 'ग्राहक पेमेंट बाकी',
  'Purchase Payment Due': 'खरेदी पेमेंट बाकी',
  'Scrap Company Payment Due': 'स्क्रॅप कंपनी पेमेंट बाकी',
  'Warranty Expiry': 'वॉरंटी समाप्ती',
  'Daily Summary': 'दैनिक सारांश',
  'Backup Reminder': 'बॅकअप स्मरणपत्र',
  'System Alert': 'सिस्टम सूचना',
  'PURCHASE STOCK': 'खरेदी स्टॉक',
  'REGULAR SALE': 'नियमित विक्री',
  'OLD BATTERY PURCHASE': 'जुनी बॅटरी खरेदी',
  'SCRAP SALES': 'स्क्रॅप विक्री',
  'Select the data you want, choose a date range, then download its PDF and prepare the email.': 'हवा असलेला डेटा निवडा, तारीख कालावधी निवडा, नंतर PDF डाउनलोड करून ईमेल तयार करा.',
  'Select Date Duration': 'तारीख कालावधी निवडा',
  'Download PDF & Email': 'PDF डाउनलोड आणि ईमेल',
  'WhatsApp Number': 'व्हाट्सअँप',
  'WhatsApp No': 'व्हाट्सअँप',
  'GST Settings': 'GST सेटिंग्ज',
  'Enter the total GST percentage. It will be divided equally between CGST and SGST everywhere in the system.': 'एकूण GST टक्केवारी प्रविष्ट करा. ती संपूर्ण प्रणालीमध्ये CGST आणि SGST मध्ये समान विभागली जाईल.',
  'Total GST (%)': 'एकूण GST (%)',
  'CGST (%)': 'CGST (%)',
  'SGST (%)': 'SGST (%)',
  'Example: Total GST 18% becomes CGST 9% + SGST 9%.': 'उदाहरण: एकूण GST 18% असल्यास CGST 9% + SGST 9% होईल.',
  'Save GST Settings': 'GST सेटिंग्ज जतन करा',
  'GST settings saved successfully.': 'GST सेटिंग्ज यशस्वीरीत्या जतन झाल्या.',
  'Brand Stock Summary': 'ब्रँडनुसार स्टॉक सारांश',
  'No brands found.': 'कोणतेही ब्रँड सापडले नाहीत.',
  'Added On': 'जोडल्याची तारीख',
  'Address:': 'पत्ता:',
  'All available bike and car stock is included automatically': 'उपलब्ध सर्व बाईक आणि कार बॅटरीचा साठा आपोआप समाविष्ट केला जातो',
  'All Battery Information': 'सर्व बॅटरी माहिती',
  'Amount Paid': 'भरलेली रक्कम',
  'Amount Paid by Company': 'कंपनीने भरलेली रक्कम',
  'Amount Paying Now (₹)': 'आता भरत असलेली रक्कम (₹)',
  'Automatic Due Amount': 'आपोआप मोजलेली बाकी रक्कम',
  'Automatic Total Amount': 'आपोआप मोजलेली एकूण रक्कम',
  'Authorised Signature': 'अधिकृत स्वाक्षरी',
  'Back to Scrap Stock': 'स्क्रॅप स्टॉकवर परत जा',
  'Balance': 'शिल्लक',
  'Based on current search': 'सध्याच्या शोधानुसार',
  'Battery Brand': 'बॅटरी ब्रँड',
  'Battery Category *': 'बॅटरी वर्ग *',
  'Battery Model': 'बॅटरी मॉडेल',
  'Battery Type': 'बॅटरी प्रकार',
  'Bike Battery': 'बाईक बॅटरी',
  'Bill To': 'बिल प्राप्तकर्ता',
  'BILL TO:': 'बिल प्राप्तकर्ता:',
  'Brand & Model': 'ब्रँड आणि मॉडेल',
  'Business Email': 'व्यवसाय ईमेल',
  'By': 'नावे',
  'Car Battery': 'कार बॅटरी',
  'Clear': 'साफ करा',
  'Close scanner': 'स्कॅनर बंद करा',
  'Closing Balance': 'अंतिम शिल्लक',
  'Closing Balance (Company Due)': 'अंतिम शिल्लक (कंपनीकडून येणे)',
  'Company Address': 'कंपनीचा पत्ता',
  'Company and Invoice': 'कंपनी आणि बिल',
  'Company Email (Optional)': 'कंपनीचा ईमेल (ऐच्छिक)',
  'Company GSTIN': 'कंपनी GSTIN',
  'Company GSTIN:': 'कंपनी GSTIN:',
  'Company Name *': 'कंपनीचे नाव *',
  'Company Name:': 'कंपनीचे नाव:',
  'Company Purchase Ledger': 'कंपनी खरेदी खातेवही',
  'Company Scrap Sale Ledger': 'कंपनी स्क्रॅप विक्री खातेवही',
  'Company:': 'कंपनी:',
  'Complete Old Stock Sale': 'जुन्या स्टॉकची विक्री पूर्ण करा',
  'Contact': 'संपर्क',
  'Contact No': 'संपर्क क्रमांक',
  'Contact No.:': 'संपर्क क्रमांक:',
  'Contact Number (Optional)': 'संपर्क क्रमांक (ऐच्छिक)',
  'Contact:': 'संपर्क:',
  'Credit (Purchase)': 'जमा (खरेदी)',
  'Credit (Scrap Sale)': 'जमा (स्क्रॅप विक्री)',
  'Customer & Battery Information': 'ग्राहक आणि बॅटरी माहिती',
  'Customer and Invoice': 'ग्राहक आणि बिल',
  'Customer Name *': 'ग्राहकाचे नाव *',
  'Customer Name / Address / Phone': 'ग्राहकाचे नाव / पत्ता / फोन',
  'Date / Invoice': 'तारीख / बिल',
  'Date Paid': 'पेमेंटची तारीख',
  'Date:': 'तारीख:',
  'Debit (Payment)': 'नावे (पेमेंट)',
  'Debit / Credit Card': 'डेबिट / क्रेडिट कार्ड',
  'Delete from scrap stock and original sales': 'स्क्रॅप स्टॉक आणि मूळ विक्रीमधून हटवा',
  'Delete sale': 'विक्री हटवा',
  'Description': 'वर्णन',
  'Discounted total minus the amount paid.': 'सवलतीनंतरच्या एकूण रकमेतून भरलेली रक्कम वजा केली आहे.',
  'Due Payment List': 'बाकी पेमेंट यादी',
  'Due:': 'बाकी:',
  'Email Id:': 'ईमेल आयडी:',
  'Email:': 'ईमेल:',
  'Enter 0 when no payment is received.': 'पेमेंट मिळाले नसल्यास 0 प्रविष्ट करा.',
  'Enter 10-digit phone number': '10 अंकी फोन क्रमांक प्रविष्ट करा',
  'Enter amount received': 'मिळालेली रक्कम प्रविष्ट करा',
  'Enter brands in the same order as the models. Known stock models fill the brand automatically.': 'मॉडेलच्या क्रमानेच ब्रँड प्रविष्ट करा. ओळखीच्या स्टॉक मॉडेलचा ब्रँड आपोआप भरला जाईल.',
  'Enter company address': 'कंपनीचा पत्ता प्रविष्ट करा',
  'Enter customer address': 'ग्राहकाचा पत्ता प्रविष्ट करा',
  'Enter customer GST number, if any': 'असल्यास ग्राहकाचा GST क्रमांक प्रविष्ट करा',
  'Enter HSN code, e.g. 8507': 'HSN कोड प्रविष्ट करा, उदा. 8507',
  'Enter HSN number': 'HSN क्रमांक प्रविष्ट करा',
  'Enter new company name': 'नवीन कंपनीचे नाव प्रविष्ट करा',
  'Enter new customer name': 'नवीन ग्राहकाचे नाव प्रविष्ट करा',
  'Enter received amount': 'मिळालेली रक्कम प्रविष्ट करा',
  'Existing Company': 'विद्यमान कंपनी',
  'Final Total': 'अंतिम एकूण',
  'G. Total:': 'अंतिम एकूण:',
  'G.Total': 'अंतिम एकूण',
  'GST Number': 'GST क्रमांक',
  'HSN Number *': 'HSN क्रमांक *',
  'Invoice No:': 'बिल क्रमांक:',
  'Invoice No.:': 'बिल क्रमांक:',
  'Kg': 'किलो',
  'Language': 'भाषा',
  'Method': 'पद्धत',
  'New Company': 'नवीन कंपनी',
  'No matching battery records found.': 'जुळणारी बॅटरी नोंद सापडली नाही.',
  'No matching customer or old battery record found.': 'जुळणारा ग्राहक किंवा जुनी बॅटरी नोंद सापडली नाही.',
  'No product records available.': 'उत्पादनाच्या नोंदी उपलब्ध नाहीत.',
  'No scrap transactions found for the selected date range.': 'निवडलेल्या कालावधीत स्क्रॅप व्यवहार सापडले नाहीत.',
  'No transactions found for the selected date range.': 'निवडलेल्या कालावधीत व्यवहार सापडले नाहीत.',
  'Old Battery Weight': 'जुन्या बॅटरीचे वजन',
  'Open company ledger': 'कंपनी खातेवही उघडा',
  'Optional': 'ऐच्छिक',
  'Pay': 'भरा',
  'Period': 'कालावधी',
  'Phone Number *': 'फोन क्रमांक *',
  'Print Ledger': 'खातेवही प्रिंट करा',
  'Print sale': 'विक्री प्रिंट करा',
  'Product Description': 'उत्पादनाचे वर्णन',
  'Product Stock Receipt': 'उत्पादन स्टॉक पावती',
  'Purchase / Payment Ledger': 'खरेदी / पेमेंट खातेवही',
  'Purchase Ledger': 'खरेदी खातेवही',
  'Purchase Price': 'खरेदी किंमत',
  'Rate per Kg': 'प्रति किलो दर',
  'Rate per Kg (₹) *': 'प्रति किलो दर (₹) *',
  'Rate Per Unit': 'प्रति युनिट दर',
  'Received Date *': 'मिळाल्याची तारीख *',
  'Record Info': 'नोंद माहिती',
  'Record payment': 'पेमेंट नोंदवा',
  'Sale Type': 'विक्री प्रकार',
  'Save Company Details': 'कंपनीचा तपशील जतन करा',
  'Save now to use this company later without creating a sale.': 'विक्री तयार न करता ही कंपनी पुढे वापरण्यासाठी आता जतन करा.',
  'Scan Model and Serial Number': 'मॉडेल आणि सिरियल क्रमांक स्कॅन करा',
  'Scrap Purchase Ledger': 'स्क्रॅप खरेदी खातेवही',
  'Search any customer or battery detail': 'कोणताही ग्राहक किंवा बॅटरी तपशील शोधा',
  'Search customer or battery...': 'ग्राहक किंवा बॅटरी शोधा...',
  'Search invoice, customer, model or serial no...': 'बिल, ग्राहक, मॉडेल किंवा सिरियल क्रमांक शोधा...',
  'Search name, phone, type, model, serial or invoice...': 'नाव, फोन, प्रकार, मॉडेल, सिरियल किंवा बिल शोधा...',
  'Select a company, edit its details if needed, then save the changes.': 'कंपनी निवडा, आवश्यक असल्यास तपशील बदला आणि बदल जतन करा.',
  'Select Ledger Date Range': 'खातेवहीचा कालावधी निवडा',
  'Select Saved Company *': 'जतन केलेली कंपनी निवडा *',
  'Select selling company': 'खरेदीदार कंपनी निवडा',
  'Selling Price': 'विक्री किंमत',
  'Serial No': 'सिरियल क्रमांक',
  'Share PDF on WhatsApp': 'WhatsApp वर PDF पाठवा',
  'Showing Batteries': 'दाखवलेल्या बॅटऱ्या',
  'Showing Weight': 'दाखवलेले वजन',
  'Sr.': 'अ.क्र.',
  'Sr.No': 'अ.क्र.',
  'Stock From': 'स्टॉक सुरुवात',
  'Stock Included': 'समाविष्ट स्टॉक',
  'Stock Period': 'स्टॉक कालावधी',
  'Stock Until': 'स्टॉक समाप्ती',
  "Today's date will be recorded automatically as the payment date.": 'आजची तारीख पेमेंटची तारीख म्हणून आपोआप नोंदवली जाईल.',
  'Total Batteries': 'एकूण बॅटऱ्या',
  'Total Entries:': 'एकूण नोंदी:',
  'Total Kg:': 'एकूण किलो:',
  'Total Qty:': 'एकूण नग:',
  'Total Quantity': 'एकूण नग',
  'Total Serial Numbers': 'एकूण सिरियल क्रमांक',
  'Type': 'प्रकार',
  'Unit Price': 'प्रति युनिट किंमत',
  'Vehicle': 'वाहन',
  'Vehicle Name:': 'वाहनाचे नाव:',
  'Vehicle No:': 'वाहन क्रमांक:',
  'View sale': 'विक्री पहा',
  'Warranty Type': 'वॉरंटी प्रकार',
  'Weight (Kg)': 'वजन (किलो)',
  'Weight (Kg) *': 'वजन (किलो) *',
  'Battery Quotation': 'बॅटरी कोटेशन',
  'Create and share battery prices with customers': 'ग्राहकांसाठी बॅटरीच्या किमती तयार करा आणि शेअर करा',
  'Enter customer name': 'ग्राहकाचे नाव प्रविष्ट करा',
  '10-digit mobile number': '१० अंकी मोबाईल क्रमांक',
  'Customer Address': 'ग्राहकाचा पत्ता',
  'Enter address': 'पत्ता प्रविष्ट करा',
  'Select battery type': 'बॅटरीचा प्रकार निवडा',
  'Quotation Type': 'कोटेशनचा प्रकार',
  '1. GST Quotation': '१. GST कोटेशन',
  'Regular batteries · GSTIN, CGST and SGST': 'नियमित बॅटरी · GSTIN, CGST आणि SGST',
  '2. Without GST': '२. GST शिवाय',
  'Secondary-market batteries · Direct grand total': 'दुय्यम बाजारातील बॅटरी · थेट अंतिम एकूण',
  'Bill to:': 'बिल प्राप्तकर्ता:',
  'Customer Name:': 'ग्राहकाचे नाव:',
  'Battery Type:': 'बॅटरीचा प्रकार:',
  'SR.': 'अ.क्र.',
  'Qty': 'नग',
  'Rate': 'दर',
  'Select brand': 'ब्रँड निवडा',
  'Select model': 'मॉडेल निवडा',
  'Battery name': 'बॅटरीचे नाव',
  'Model name': 'मॉडेलचे नाव',
  'Warranty: 15F + 12P': 'वॉरंटी: 15F + 12P',
  'Enter G.Total': 'अंतिम एकूण प्रविष्ट करा',
  'Add another battery': 'आणखी एक बॅटरी जोडा',
  'Enter details': 'तपशील प्रविष्ट करा',
  'Fill customer and battery information': 'ग्राहक आणि बॅटरीची माहिती भरा',
  'Print / Save PDF': 'प्रिंट / PDF जतन करा',
  'Send on WhatsApp': 'WhatsApp वर पाठवा',
  'Inverter Battery': 'इन्व्हर्टर बॅटरी',
  'Truck Battery': 'ट्रक बॅटरी',
  'Commercial Vehicle Battery': 'व्यावसायिक वाहन बॅटरी',
  'Solar Battery': 'सौर बॅटरी',
})

// Complete Marathi coverage for the Quotation screen.
Object.assign(mr, {
  'Quotation': 'कोटेशन',
  'Battery Quotation': 'बॅटरी कोटेशन',
  'Create and share battery prices with customers': 'ग्राहकांसाठी बॅटरीच्या किमती तयार करा आणि शेअर करा',
  'New Customer': 'नवीन ग्राहक',
  'Existing Customer': 'विद्यमान ग्राहक',
  'Select Existing Customer': 'विद्यमान ग्राहक निवडा',
  'select existing customer': 'विद्यमान ग्राहक निवडा',
  'Select customer': 'ग्राहक निवडा',
  'select customer': 'ग्राहक निवडा',
  'Only customer details are reused. Previous quotation items and prices are never copied.': 'फक्त ग्राहकाची माहिती वापरली जाईल. मागील कोटेशनमधील वस्तू आणि किमती कॉपी केल्या जाणार नाहीत.',
  'Customer Name': 'ग्राहकाचे नाव',
  'WhatsApp Number': 'व्हॉट्सअॅप क्रमांक',
  'Customer Address': 'ग्राहकाचा पत्ता',
  'Customer GSTIN': 'ग्राहक GSTIN',
  'Type of Battery': 'बॅटरीचा प्रकार',
  'Quotation Type': 'कोटेशनचा प्रकार',
  'Enter customer name': 'ग्राहकाचे नाव प्रविष्ट करा',
  '10-digit mobile number': '१० अंकी मोबाईल क्रमांक',
  'Enter address': 'पत्ता प्रविष्ट करा',
  'Enter GSTIN if available': 'GSTIN असल्यास प्रविष्ट करा',
  'Select or type battery type': 'बॅटरीचा प्रकार निवडा किंवा लिहा',
  '1. GST Quotation': '१. GST कोटेशन',
  'Regular batteries · GSTIN, CGST and SGST': 'नियमित बॅटरी · GSTIN, CGST आणि SGST',
  '2. Without GST': '२. GST शिवाय',
  'Secondary-market batteries · Direct grand total': 'दुय्यम बाजारातील बॅटरी · थेट एकूण रक्कम',
  'Brand Name *': 'ब्रँडचे नाव *',
  'Product Description *': 'उत्पादनाचे वर्णन *',
  'Product Description': 'उत्पादनाचे वर्णन',
  'Qty *': 'नग *',
  'Grand Total *': 'एकूण रक्कम *',
  'Grand Total': 'एकूण रक्कम',
  'Select brand': 'ब्रँड निवडा',
  'Search or select model': 'मॉडेल शोधा किंवा निवडा',
  'Select brand first': 'प्रथम ब्रँड निवडा',
  'select brand first': 'प्रथम ब्रँड निवडा',
  'Show model options': 'मॉडेलचे पर्याय दाखवा',
  'No matching models': 'जुळणारे मॉडेल सापडले नाही',
  'Enter full battery name': 'बॅटरीचे पूर्ण नाव प्रविष्ट करा',
  'Enter full product description': 'उत्पादनाचे पूर्ण वर्णन प्रविष्ट करा',
  'Warranty': 'वॉरंटी',
  'Warranty: 15F + 12P': 'वॉरंटी: 15F + 12P',
  'Enter G.Total': 'एकूण रक्कम प्रविष्ट करा',
  'Add model for this brand': 'या ब्रँडसाठी मॉडेल जोडा',
  'Remove battery': 'बॅटरी काढा',
  'Add another brand / model': 'आणखी एक ब्रँड / मॉडेल जोडा',
  'Print Language': 'प्रिंट भाषा',
  'Print / Save PDF': 'प्रिंट / PDF जतन करा',
  'Creating PDF...': 'PDF तयार होत आहे...',
  'Send PDF on WhatsApp': 'PDF व्हॉट्सअॅपवर पाठवा',
  'Sign in to Send Quotation': 'कोटेशन पाठवण्यासाठी साइन इन करा',
  'Supabase Admin Email': 'ॲडमिन ईमेल',
  'Supabase Admin Password': 'ॲडमिन पासवर्ड',
  'Login & Send PDF Link': 'लॉगिन करा आणि PDF लिंक पाठवा',
  'Signing in...': 'साइन इन होत आहे...',
})

const translations = { en: {}, mr }
const LanguageContext = createContext(null)

function translateText(text, language) {
  if (language !== 'mr') return text
  return translations.mr[text] || text
}

function shouldSkipNode(node) {
  const parent = node.parentElement
  if (!parent) return true
  if (parent.closest('script, style, textarea, input, canvas, svg')) return true
  if (parent.closest('[data-no-translate]')) return true
  return false
}

const originalTextCache = new WeakMap()
const originalAttributeCache = new WeakMap()

function translateElementText(root, language) {
  if (!root) return
  if (root.querySelector?.('[data-standalone-language]')) return
  document.documentElement.lang = language === 'mr' ? 'mr' : 'en'

  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
    acceptNode(node) {
      if (shouldSkipNode(node)) return NodeFilter.FILTER_REJECT
      return String(node.nodeValue || '').trim() ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_REJECT
    },
  })

  const nodes = []
  while (walker.nextNode()) nodes.push(walker.currentNode)

  nodes.forEach((node) => {
    if (!originalTextCache.has(node)) {
      originalTextCache.set(node, node.nodeValue)
    }
    const original = originalTextCache.get(node)
    const key = String(original || '').trim()
    if (!key) return
    node.nodeValue = language === 'mr'
      ? String(original).replace(key, translateText(key, language))
      : original
  })

  root.querySelectorAll?.('[placeholder], [title], [aria-label]').forEach((element) => {
    if (element.closest('[data-no-translate]')) return
    if (!originalAttributeCache.has(element)) originalAttributeCache.set(element, {})
    const cache = originalAttributeCache.get(element)
    ;['placeholder', 'title', 'aria-label'].forEach((attribute) => {
      if (!element.hasAttribute(attribute)) return
      if (!(attribute in cache)) cache[attribute] = element.getAttribute(attribute)
      const original = cache[attribute]
      element.setAttribute(attribute, translateText(original, language))
    })
  })
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => localStorage.getItem('kb-language') || 'en')
  const [theme, setThemeState] = useState(() => localStorage.getItem('kb-theme') || 'light')
  const observerRef = useRef(null)
  const timerRef = useRef(null)

  function setLanguage(nextLanguage) {
    setLanguageState(nextLanguage)
    localStorage.setItem('kb-language', nextLanguage)
  }

  function setTheme(nextTheme) {
    setThemeState(nextTheme)
    localStorage.setItem('kb-theme', nextTheme)
  }

  useEffect(() => {
    document.documentElement.dataset.theme = theme
  }, [theme])

  useEffect(() => {
    const scheduleTranslate = () => {
      window.clearTimeout(timerRef.current)
      timerRef.current = window.setTimeout(() => translateElementText(document.body, language), 80)
    }

    scheduleTranslate()
    observerRef.current?.disconnect()
    observerRef.current = new MutationObserver(scheduleTranslate)
    observerRef.current.observe(document.body, { childList: true, subtree: true })

    return () => {
      window.clearTimeout(timerRef.current)
      observerRef.current?.disconnect()
    }
  }, [language])

  const value = useMemo(() => ({
    language,
    setLanguage,
    theme,
    setTheme,
    t: (text) => translateText(text, language),
  }), [language, theme])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider')
  return context
}
